// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
)

const TypeArticle authz.Type = "extsvc/article"
type RelationArticle authz.Relation
type PermissionArticle authz.Permission

const ArticleAuthor RelationArticle = "author"
type ArticleAuthorObjects struct {
  User []User
}

type Article authz.ID
func ArticleStringer(id authz.StringConvertable) Article {
  return Article(id.String())
}

func ArticleStringers(ids ...authz.StringConvertable) []Article {
  result := []Article{}
  for _, id := range ids {
    result = append(result, Article(id.String()))
  }
  return result
}

func (article Article) ToList() []Article {
  return []Article{ article }
}

func (article Article) CreateAuthorRelations(ctx context.Context, objects ArticleAuthorObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    }, authz.Relation(ArticleAuthor), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (article Article) DeleteAuthorRelations(ctx context.Context, objects ArticleAuthorObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    }, authz.Relation(ArticleAuthor), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (article Article) ReadAuthorUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeArticle,
    ID: authz.ID(article),
  }, authz.Relation(ArticleAuthor), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

const ArticleManage PermissionArticle = "manage"

type CheckArticleManageInputs struct {
  User []User
}

func (article Article) CheckManage(ctx context.Context, input CheckArticleManageInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    }, authz.Permission(ArticleManage), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupManageArticleResources(ctx context.Context, input CheckArticleManageInputs) ([]Article, error) {
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeArticle, authz.Permission(ArticleManage), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Article](ids), nil
  }
  
  return []Article{}, nil
}
const ArticleAuthorOnly PermissionArticle = "author_only"

type CheckArticleAuthorOnlyInputs struct {
  User []User
}

func (article Article) CheckAuthorOnly(ctx context.Context, input CheckArticleAuthorOnlyInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    }, authz.Permission(ArticleAuthorOnly), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupAuthorOnlyArticleResources(ctx context.Context, input CheckArticleAuthorOnlyInputs) ([]Article, error) {
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeArticle, authz.Permission(ArticleAuthorOnly), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Article](ids), nil
  }
  
  return []Article{}, nil
}

func (article Article) LookupManageUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    },
    authz.Permission(ArticleManage), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (article Article) LookupManageUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    },
    authz.Permission(ArticleManage), TypeUser,
  )
}

func (article Article) LookupAuthorOnlyUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    },
    authz.Permission(ArticleAuthorOnly), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (article Article) LookupAuthorOnlyUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeArticle,
      ID: authz.ID(article),
    },
    authz.Permission(ArticleAuthorOnly), TypeUser,
  )
}
