// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
)

const TypeDocument authz.Type = "extsvc/document"
type RelationDocument authz.Relation
type PermissionDocument authz.Permission

const DocumentParent RelationDocument = "parent"
type DocumentParentObjects struct {
  Folder []Folder
}
const DocumentOwner RelationDocument = "owner"
type DocumentOwnerObjects struct {
  User []User
  Group []Group
}

type Document authz.ID
func DocumentStringer(id authz.StringConvertable) Document {
  return Document(id.String())
}

func DocumentStringers(ids ...authz.StringConvertable) []Document {
  result := []Document{}
  for _, id := range ids {
    result = append(result, Document(id.String()))
  }
  return result
}

func (document Document) ToList() []Document {
  return []Document{ document }
}

func (document Document) CreateParentRelations(ctx context.Context, objects DocumentParentObjects) error {
  if len(objects.Folder) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentParent), TypeFolder, authz.IDs(objects.Folder))
    if err != nil {
      return err
    }
  }
  return nil
}
func (document Document) CreateOwnerRelations(ctx context.Context, objects DocumentOwnerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentOwner), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentOwner), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  return nil
}

func (document Document) DeleteParentRelations(ctx context.Context, objects DocumentParentObjects) error {
  if len(objects.Folder) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentParent), TypeFolder, authz.IDs(objects.Folder))
    if err != nil {
      return err
    }
  }
  return nil
}

func (document Document) DeleteOwnerRelations(ctx context.Context, objects DocumentOwnerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentOwner), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Relation(DocumentOwner), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  return nil
}

func (document Document) ReadParentFolderRelations(ctx context.Context) ([]Folder, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeDocument,
    ID: authz.ID(document),
  }, authz.Relation(DocumentParent), TypeFolder)
  if err != nil {
    return nil, err
  }
  
  return authz.FromIDs[Folder](ids), nil
}

func (document Document) ReadOwnerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeDocument,
    ID: authz.ID(document),
  }, authz.Relation(DocumentOwner), TypeUser)
  if err != nil {
    return nil, err
  }
  
  return authz.FromIDs[User](ids), nil
}

func (document Document) ReadOwnerGroupRelations(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeDocument,
    ID: authz.ID(document),
  }, authz.Relation(DocumentOwner), TypeGroup)
  if err != nil {
    return nil, err
  }
  
  return authz.FromIDs[Group](ids), nil
}

const DocumentView PermissionDocument = "view"

type CheckDocumentViewInputs struct {
  User []User
  Group []Group
  Role []Role
}

func (document Document) CheckView(ctx context.Context, input CheckDocumentViewInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && len(input.Role) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentView), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentView), TypeGroup, authz.IDs(input.Group))
    if err != nil {
      return false, err
    }
  }
  if len(input.Role) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentView), TypeRole, authz.IDs(input.Role))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupViewDocumentResources(ctx context.Context, input CheckDocumentViewInputs) ([]Document, error) {
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentView), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentView), 
      TypeGroup, authz.IDs(input.Group),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  if len(input.Role) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentView), 
      TypeRole, authz.IDs(input.Role),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  
  return []Document{}, nil
}
const DocumentEdit PermissionDocument = "edit"

type CheckDocumentEditInputs struct {
  User []User
  Group []Group
  Role []Role
}

func (document Document) CheckEdit(ctx context.Context, input CheckDocumentEditInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && len(input.Role) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentEdit), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentEdit), TypeGroup, authz.IDs(input.Group))
    if err != nil {
      return false, err
    }
  }
  if len(input.Role) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentEdit), TypeRole, authz.IDs(input.Role))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupEditDocumentResources(ctx context.Context, input CheckDocumentEditInputs) ([]Document, error) {
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentEdit), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentEdit), 
      TypeGroup, authz.IDs(input.Group),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  if len(input.Role) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentEdit), 
      TypeRole, authz.IDs(input.Role),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  
  return []Document{}, nil
}
const DocumentAdmin PermissionDocument = "admin"

type CheckDocumentAdminInputs struct {
  User []User
  Group []Group
}

func (document Document) CheckAdmin(ctx context.Context, input CheckDocumentAdminInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentAdmin), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, authz.Permission(DocumentAdmin), TypeGroup, authz.IDs(input.Group))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupAdminDocumentResources(ctx context.Context, input CheckDocumentAdminInputs) ([]Document, error) {
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentAdmin), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeDocument, authz.Permission(DocumentAdmin), 
      TypeGroup, authz.IDs(input.Group),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Document](ids), nil
  }
  
  return []Document{}, nil
}

func (document Document) LookupViewUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentView), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[User](ids), nil
}
func (document Document) LookupViewGroupSubjects(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentView), TypeGroup,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[Group](ids), nil
}
func (document Document) LookupViewRoleSubjects(ctx context.Context) ([]Role, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentView), TypeRole,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[Role](ids), nil
}

func (document Document) LookupEditUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentEdit), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[User](ids), nil
}
func (document Document) LookupEditGroupSubjects(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentEdit), TypeGroup,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[Group](ids), nil
}
func (document Document) LookupEditRoleSubjects(ctx context.Context) ([]Role, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentEdit), TypeRole,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[Role](ids), nil
}

func (document Document) LookupAdminUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentAdmin), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[User](ids), nil
}
func (document Document) LookupAdminGroupSubjects(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeDocument,
      ID: authz.ID(document),
    }, 
    authz.Permission(DocumentAdmin), TypeGroup,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDs[Group](ids), nil
}
