// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "time"
)

const TypeFolder authz.Type = "extsvc/folder"
type RelationFolder authz.Relation
type PermissionFolder authz.Permission

const FolderViewer RelationFolder = "viewer"
type FolderViewerObjects struct {
  User []User
  Group []Group
  Role []Role
}
const FolderGuest RelationFolder = "guest"
type FolderGuestObjects struct {
  User []User
  Wildcards FolderGuestWildcards
}
type FolderGuestWildcards struct {
  User bool
}
const FolderTenantedViewer RelationFolder = "tenanted_viewer"
type FolderTenantedViewerObjects struct {
  User []User
  Caveats FolderTenantedViewerCaveats
}
type FolderTenantedViewerCaveats struct {
  User *TenantMatchArgs
}
const FolderGuardedViewer RelationFolder = "guarded_viewer"
type FolderGuardedViewerObjects struct {
  User []User
  Wildcards FolderGuardedViewerWildcards
  Caveats FolderGuardedViewerCaveats
}
type FolderGuardedViewerWildcards struct {
  User bool
}
type FolderGuardedViewerCaveats struct {
  User *TenantMatchArgs
}
const FolderActor RelationFolder = "actor"
type FolderActorObjects struct {
  User []User
  Caveats FolderActorCaveats
}
type FolderActorCaveats struct {
  User *WithinWindowArgs
}
const FolderCollaborator RelationFolder = "collaborator"
type FolderCollaboratorObjects struct {
  User []User
  Group []Group
  Caveats FolderCollaboratorCaveats
}
type FolderCollaboratorCaveats struct {
  User *WithinWindowArgs
}
const FolderRateLimited RelationFolder = "rate_limited"
type FolderRateLimitedObjects struct {
  User []User
  Caveats FolderRateLimitedCaveats
}
type FolderRateLimitedCaveats struct {
  User *QuotaCheckArgs
}
const FolderScoredViewer RelationFolder = "scored_viewer"
type FolderScoredViewerObjects struct {
  User []User
  Caveats FolderScoredViewerCaveats
}
type FolderScoredViewerCaveats struct {
  User *MinScoreArgs
}
const FolderTokenViewer RelationFolder = "token_viewer"
type FolderTokenViewerObjects struct {
  User []User
  Caveats FolderTokenViewerCaveats
}
type FolderTokenViewerCaveats struct {
  User *HasTokenArgs
}
const FolderVersionedViewer RelationFolder = "versioned_viewer"
type FolderVersionedViewerObjects struct {
  User []User
  Caveats FolderVersionedViewerCaveats
}
type FolderVersionedViewerCaveats struct {
  User *VersionCheckArgs
}
const FolderMatrixViewer RelationFolder = "matrix_viewer"
type FolderMatrixViewerObjects struct {
  User []User
  Caveats FolderMatrixViewerCaveats
}
type FolderMatrixViewerCaveats struct {
  User *MatrixCheckArgs
}
const FolderTenantedUser RelationFolder = "tenanted_user"
type FolderTenantedUserObjects struct {
  User []User
  Caveats FolderTenantedUserCaveats
}
type FolderTenantedUserCaveats struct {
  User *TenantMatchArgs
}
const FolderWindowedUser RelationFolder = "windowed_user"
type FolderWindowedUserObjects struct {
  User []User
  Caveats FolderWindowedUserCaveats
}
type FolderWindowedUserCaveats struct {
  User *WithinWindowArgs
}
const FolderGatedRoot RelationFolder = "gated_root"
type FolderGatedRootObjects struct {
  Folder []Folder
  Caveats FolderGatedRootCaveats
}
type FolderGatedRootCaveats struct {
  Folder *TenantMatchArgs
}
const FolderExpiringViewer RelationFolder = "expiring_viewer"
type FolderExpiringViewerObjects struct {
  User []User
  Expirations FolderExpiringViewerExpirations
}
type FolderExpiringViewerExpirations struct {
  User *time.Time
}
const FolderGatedToken RelationFolder = "gated_token"
type FolderGatedTokenObjects struct {
  User []User
  Caveats FolderGatedTokenCaveats
  Expirations FolderGatedTokenExpirations
}
type FolderGatedTokenCaveats struct {
  User *TenantMatchArgs
}
type FolderGatedTokenExpirations struct {
  User *time.Time
}
const FolderPublicUntil RelationFolder = "public_until"
type FolderPublicUntilObjects struct {
  User []User
  Wildcards FolderPublicUntilWildcards
  Expirations FolderPublicUntilExpirations
}
type FolderPublicUntilWildcards struct {
  User bool
}
type FolderPublicUntilExpirations struct {
  User *time.Time
}
const FolderPublicGated RelationFolder = "public_gated"
type FolderPublicGatedObjects struct {
  User []User
  Wildcards FolderPublicGatedWildcards
  Caveats FolderPublicGatedCaveats
  Expirations FolderPublicGatedExpirations
}
type FolderPublicGatedWildcards struct {
  User bool
}
type FolderPublicGatedCaveats struct {
  User *TenantMatchArgs
}
type FolderPublicGatedExpirations struct {
  User *time.Time
}
type HasTokenArgs struct {
  Token []byte
}

type MatrixCheckArgs struct {
  Rows [][]string
}

type MinScoreArgs struct {
  Current *float64
  MinRequired *float64
}

type QuotaCheckArgs struct {
  MaxUses *int
  WithinQuota *bool
}

type TenantMatchArgs struct {
  Tenant *string
}

type VersionCheckArgs struct {
  MinVersion *uint
}

type WithinWindowArgs struct {
  AllowedActions []string
  RequestedAction *string
}


type Folder authz.ID
func FolderStringer(id authz.StringConvertable) Folder {
  return Folder(id.String())
}

func FolderStringers(ids ...authz.StringConvertable) []Folder {
  result := []Folder{}
  for _, id := range ids {
    result = append(result, Folder(id.String()))
  }
  return result
}

func (folder Folder) ToList() []Folder {
  return []Folder{ folder }
}

func (folder Folder) CreateViewerRelations(ctx context.Context, objects FolderViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  if len(objects.Role) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeRole, authz.IDs(objects.Role))
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateGuestRelations(ctx context.Context, objects FolderGuestObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuest), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuest), TypeUser, []authz.ID{authz.WildcardID})
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateTenantedViewerRelations(ctx context.Context, objects FolderTenantedViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTenantedViewer), TypeUser, authz.IDs(objects.User), "extsvc/tenant_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateGuardedViewerRelations(ctx context.Context, objects FolderGuardedViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuardedViewer), TypeUser, authz.IDs(objects.User), "extsvc/tenant_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuardedViewer), TypeUser, []authz.ID{authz.WildcardID}, "extsvc/tenant_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateActorRelations(ctx context.Context, objects FolderActorObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.AllowedActions != nil {
        caveatCtx["allowed_actions"] = c.AllowedActions
      }
      if c.RequestedAction != nil {
        caveatCtx["requested_action"] = *c.RequestedAction
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderActor), TypeUser, authz.IDs(objects.User), "extsvc/within_window", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateCollaboratorRelations(ctx context.Context, objects FolderCollaboratorObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.AllowedActions != nil {
        caveatCtx["allowed_actions"] = c.AllowedActions
      }
      if c.RequestedAction != nil {
        caveatCtx["requested_action"] = *c.RequestedAction
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderCollaborator), TypeUser, authz.IDs(objects.User), "extsvc/within_window", caveatCtx)
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderCollaborator), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateRateLimitedRelations(ctx context.Context, objects FolderRateLimitedObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.MaxUses != nil {
        caveatCtx["max_uses"] = *c.MaxUses
      }
      if c.WithinQuota != nil {
        caveatCtx["within_quota"] = *c.WithinQuota
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderRateLimited), TypeUser, authz.IDs(objects.User), "extsvc/quota_check", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateScoredViewerRelations(ctx context.Context, objects FolderScoredViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Current != nil {
        caveatCtx["current"] = *c.Current
      }
      if c.MinRequired != nil {
        caveatCtx["min_required"] = *c.MinRequired
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderScoredViewer), TypeUser, authz.IDs(objects.User), "extsvc/min_score", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateTokenViewerRelations(ctx context.Context, objects FolderTokenViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Token != nil {
        caveatCtx["token"] = c.Token
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTokenViewer), TypeUser, authz.IDs(objects.User), "extsvc/has_token", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateVersionedViewerRelations(ctx context.Context, objects FolderVersionedViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.MinVersion != nil {
        caveatCtx["min_version"] = *c.MinVersion
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderVersionedViewer), TypeUser, authz.IDs(objects.User), "extsvc/version_check", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateMatrixViewerRelations(ctx context.Context, objects FolderMatrixViewerObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Rows != nil {
        caveatCtx["rows"] = c.Rows
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderMatrixViewer), TypeUser, authz.IDs(objects.User), "extsvc/matrix_check", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateTenantedUserRelations(ctx context.Context, objects FolderTenantedUserObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTenantedUser), TypeUser, authz.IDs(objects.User), "extsvc/tenant_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateWindowedUserRelations(ctx context.Context, objects FolderWindowedUserObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.AllowedActions != nil {
        caveatCtx["allowed_actions"] = c.AllowedActions
      }
      if c.RequestedAction != nil {
        caveatCtx["requested_action"] = *c.RequestedAction
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderWindowedUser), TypeUser, authz.IDs(objects.User), "extsvc/within_window", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateGatedRootRelations(ctx context.Context, objects FolderGatedRootObjects) error {
  if len(objects.Folder) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.Folder; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGatedRoot), TypeFolder, authz.IDs(objects.Folder), "extsvc/tenant_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateExpiringViewerRelations(ctx context.Context, objects FolderExpiringViewerObjects) error {
  if len(objects.User) > 0 {
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderExpiringViewer), TypeUser, authz.IDs(objects.User), "", nil, expiresAt)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreateGatedTokenRelations(ctx context.Context, objects FolderGatedTokenObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGatedToken), TypeUser, authz.IDs(objects.User), "extsvc/tenant_match", caveatCtx, expiresAt)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreatePublicUntilRelations(ctx context.Context, objects FolderPublicUntilObjects) error {
  if len(objects.User) > 0 {
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicUntil), TypeUser, authz.IDs(objects.User), "", nil, expiresAt)
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicUntil), TypeUser, []authz.ID{authz.WildcardID}, "", nil, expiresAt)
    if err != nil {
      return err
    }
  }
  return nil
}
func (folder Folder) CreatePublicGatedRelations(ctx context.Context, objects FolderPublicGatedObjects) error {
  if len(objects.User) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicGated), TypeUser, authz.IDs(objects.User), "extsvc/tenant_match", caveatCtx, expiresAt)
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    var caveatCtx map[string]any
    if c := objects.Caveats.User; c != nil {
      caveatCtx = map[string]any{}
      if c.Tenant != nil {
        caveatCtx["tenant"] = *c.Tenant
      }
    }
    var expiresAt time.Time
    if e := objects.Expirations.User; e != nil {
      expiresAt = *e
    }
    err := authz.GetEngine(ctx).CreateRelationsWithExpiration(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicGated), TypeUser, []authz.ID{authz.WildcardID}, "extsvc/tenant_match", caveatCtx, expiresAt)
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteViewerRelations(ctx context.Context, objects FolderViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  if len(objects.Role) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderViewer), TypeRole, authz.IDs(objects.Role))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteGuestRelations(ctx context.Context, objects FolderGuestObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuest), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuest), TypeUser, []authz.ID{authz.WildcardID})
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteTenantedViewerRelations(ctx context.Context, objects FolderTenantedViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTenantedViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteGuardedViewerRelations(ctx context.Context, objects FolderGuardedViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuardedViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGuardedViewer), TypeUser, []authz.ID{authz.WildcardID})
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteActorRelations(ctx context.Context, objects FolderActorObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderActor), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteCollaboratorRelations(ctx context.Context, objects FolderCollaboratorObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderCollaborator), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if len(objects.Group) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderCollaborator), TypeGroup, authz.IDs(objects.Group))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteRateLimitedRelations(ctx context.Context, objects FolderRateLimitedObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderRateLimited), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteScoredViewerRelations(ctx context.Context, objects FolderScoredViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderScoredViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteTokenViewerRelations(ctx context.Context, objects FolderTokenViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTokenViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteVersionedViewerRelations(ctx context.Context, objects FolderVersionedViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderVersionedViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteMatrixViewerRelations(ctx context.Context, objects FolderMatrixViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderMatrixViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteTenantedUserRelations(ctx context.Context, objects FolderTenantedUserObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderTenantedUser), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteWindowedUserRelations(ctx context.Context, objects FolderWindowedUserObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderWindowedUser), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteGatedRootRelations(ctx context.Context, objects FolderGatedRootObjects) error {
  if len(objects.Folder) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGatedRoot), TypeFolder, authz.IDs(objects.Folder))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteExpiringViewerRelations(ctx context.Context, objects FolderExpiringViewerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderExpiringViewer), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeleteGatedTokenRelations(ctx context.Context, objects FolderGatedTokenObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderGatedToken), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeletePublicUntilRelations(ctx context.Context, objects FolderPublicUntilObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicUntil), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicUntil), TypeUser, []authz.ID{authz.WildcardID})
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) DeletePublicGatedRelations(ctx context.Context, objects FolderPublicGatedObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicGated), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  if objects.Wildcards.User {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Relation(FolderPublicGated), TypeUser, []authz.ID{authz.WildcardID})
    if err != nil {
      return err
    }
  }
  return nil
}

func (folder Folder) ReadViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadViewerGroupRelations(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderViewer), TypeGroup)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Group](ids), nil
}

func (folder Folder) ReadViewerRoleRelations(ctx context.Context) ([]Role, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderViewer), TypeRole)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Role](ids), nil
}

func (folder Folder) ReadGuestUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGuest), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}
func (folder Folder) ReadGuestUserWildcard(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicRelation(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGuest), TypeUser)
}

func (folder Folder) ReadTenantedViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderTenantedViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadGuardedViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGuardedViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}
func (folder Folder) ReadGuardedViewerUserWildcard(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicRelation(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGuardedViewer), TypeUser)
}

func (folder Folder) ReadActorUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderActor), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadCollaboratorUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderCollaborator), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadCollaboratorGroupRelations(ctx context.Context) ([]Group, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderCollaborator), TypeGroup)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Group](ids), nil
}

func (folder Folder) ReadRateLimitedUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderRateLimited), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadScoredViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderScoredViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadTokenViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderTokenViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadVersionedViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderVersionedViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadMatrixViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderMatrixViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadTenantedUserUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderTenantedUser), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadWindowedUserUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderWindowedUser), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadGatedRootFolderRelations(ctx context.Context) ([]Folder, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGatedRoot), TypeFolder)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Folder](ids), nil
}

func (folder Folder) ReadExpiringViewerUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderExpiringViewer), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadGatedTokenUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderGatedToken), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) ReadPublicUntilUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderPublicUntil), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}
func (folder Folder) ReadPublicUntilUserWildcard(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicRelation(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderPublicUntil), TypeUser)
}

func (folder Folder) ReadPublicGatedUserRelations(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderPublicGated), TypeUser)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}
func (folder Folder) ReadPublicGatedUserWildcard(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicRelation(ctx, authz.Resource{
    Type: TypeFolder,
    ID: authz.ID(folder),
  }, authz.Relation(FolderPublicGated), TypeUser)
}

const FolderBrowse PermissionFolder = "browse"

type CheckFolderBrowseInputs struct {
  User []User
  Group []Group
  Role []Role
}

func (folder Folder) CheckBrowse(ctx context.Context, input CheckFolderBrowseInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && len(input.Role) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderBrowse), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderBrowse), TypeGroup, authz.IDs(input.Group))
    if err != nil {
      return false, err
    }
  }
  if len(input.Role) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderBrowse), TypeRole, authz.IDs(input.Role))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupBrowseFolderResources(ctx context.Context, input CheckFolderBrowseInputs) ([]Folder, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeFolder, authz.Permission(FolderBrowse),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeFolder, authz.Permission(FolderBrowse),
      TypeGroup, authz.IDs(input.Group),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  if len(input.Role) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeFolder, authz.Permission(FolderBrowse),
      TypeRole, authz.IDs(input.Role),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderTenantedBrowse PermissionFolder = "tenanted_browse"

type CheckFolderTenantedBrowseInputs struct {
  User []User
  Caveats CheckFolderTenantedBrowseCaveats
}
type CheckFolderTenantedBrowseCaveats struct {
  TenantMatch *TenantMatchArgs
}

func (folder Folder) CheckTenantedBrowse(ctx context.Context, input CheckFolderTenantedBrowseInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderTenantedBrowse), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupTenantedBrowseFolderResources(ctx context.Context, input CheckFolderTenantedBrowseInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderTenantedBrowse),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderGuardedBrowse PermissionFolder = "guarded_browse"

type CheckFolderGuardedBrowseInputs struct {
  User []User
  Caveats CheckFolderGuardedBrowseCaveats
}
type CheckFolderGuardedBrowseCaveats struct {
  TenantMatch *TenantMatchArgs
}

func (folder Folder) CheckGuardedBrowse(ctx context.Context, input CheckFolderGuardedBrowseInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderGuardedBrowse), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupGuardedBrowseFolderResources(ctx context.Context, input CheckFolderGuardedBrowseInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderGuardedBrowse),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderAct PermissionFolder = "act"

type CheckFolderActInputs struct {
  User []User
  Caveats CheckFolderActCaveats
}
type CheckFolderActCaveats struct {
  WithinWindow *WithinWindowArgs
}

func (folder Folder) CheckAct(ctx context.Context, input CheckFolderActInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderAct), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupActFolderResources(ctx context.Context, input CheckFolderActInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderAct),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderCollaborate PermissionFolder = "collaborate"

type CheckFolderCollaborateInputs struct {
  User []User
  Group []Group
  Caveats CheckFolderCollaborateCaveats
}
type CheckFolderCollaborateCaveats struct {
  WithinWindow *WithinWindowArgs
}

func (folder Folder) CheckCollaborate(ctx context.Context, input CheckFolderCollaborateInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderCollaborate), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderCollaborate), TypeGroup, authz.IDs(input.Group), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupCollaborateFolderResources(ctx context.Context, input CheckFolderCollaborateInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderCollaborate),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderCollaborate),
      TypeGroup, authz.IDs(input.Group),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderRateCheck PermissionFolder = "rate_check"

type CheckFolderRateCheckInputs struct {
  User []User
  Caveats CheckFolderRateCheckCaveats
}
type CheckFolderRateCheckCaveats struct {
  QuotaCheck *QuotaCheckArgs
}

func (folder Folder) CheckRateCheck(ctx context.Context, input CheckFolderRateCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.QuotaCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MaxUses != nil {
      caveatCtx["max_uses"] = *c.MaxUses
    }
    if c.WithinQuota != nil {
      caveatCtx["within_quota"] = *c.WithinQuota
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderRateCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupRateCheckFolderResources(ctx context.Context, input CheckFolderRateCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.QuotaCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MaxUses != nil {
      caveatCtx["max_uses"] = *c.MaxUses
    }
    if c.WithinQuota != nil {
      caveatCtx["within_quota"] = *c.WithinQuota
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderRateCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderScoreCheck PermissionFolder = "score_check"

type CheckFolderScoreCheckInputs struct {
  User []User
  Caveats CheckFolderScoreCheckCaveats
}
type CheckFolderScoreCheckCaveats struct {
  MinScore *MinScoreArgs
}

func (folder Folder) CheckScoreCheck(ctx context.Context, input CheckFolderScoreCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderScoreCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupScoreCheckFolderResources(ctx context.Context, input CheckFolderScoreCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderScoreCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderTokenCheck PermissionFolder = "token_check"

type CheckFolderTokenCheckInputs struct {
  User []User
  Caveats CheckFolderTokenCheckCaveats
}
type CheckFolderTokenCheckCaveats struct {
  HasToken *HasTokenArgs
}

func (folder Folder) CheckTokenCheck(ctx context.Context, input CheckFolderTokenCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderTokenCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupTokenCheckFolderResources(ctx context.Context, input CheckFolderTokenCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderTokenCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderVersionCheckPerm PermissionFolder = "version_check_perm"

type CheckFolderVersionCheckPermInputs struct {
  User []User
  Caveats CheckFolderVersionCheckPermCaveats
}
type CheckFolderVersionCheckPermCaveats struct {
  VersionCheck *VersionCheckArgs
}

func (folder Folder) CheckVersionCheckPerm(ctx context.Context, input CheckFolderVersionCheckPermInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.VersionCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MinVersion != nil {
      caveatCtx["min_version"] = *c.MinVersion
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderVersionCheckPerm), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupVersionCheckPermFolderResources(ctx context.Context, input CheckFolderVersionCheckPermInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.VersionCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MinVersion != nil {
      caveatCtx["min_version"] = *c.MinVersion
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderVersionCheckPerm),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderMatrixCheckPerm PermissionFolder = "matrix_check_perm"

type CheckFolderMatrixCheckPermInputs struct {
  User []User
  Caveats CheckFolderMatrixCheckPermCaveats
}
type CheckFolderMatrixCheckPermCaveats struct {
  MatrixCheck *MatrixCheckArgs
}

func (folder Folder) CheckMatrixCheckPerm(ctx context.Context, input CheckFolderMatrixCheckPermInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.MatrixCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Rows != nil {
      caveatCtx["rows"] = c.Rows
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderMatrixCheckPerm), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupMatrixCheckPermFolderResources(ctx context.Context, input CheckFolderMatrixCheckPermInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.MatrixCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Rows != nil {
      caveatCtx["rows"] = c.Rows
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderMatrixCheckPerm),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderMultiCheck PermissionFolder = "multi_check"

type CheckFolderMultiCheckInputs struct {
  User []User
  Caveats CheckFolderMultiCheckCaveats
}
type CheckFolderMultiCheckCaveats struct {
  TenantMatch *TenantMatchArgs
  WithinWindow *WithinWindowArgs
}

func (folder Folder) CheckMultiCheck(ctx context.Context, input CheckFolderMultiCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderMultiCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupMultiCheckFolderResources(ctx context.Context, input CheckFolderMultiCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }
  if c := input.Caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderMultiCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderViaGatedRoot PermissionFolder = "via_gated_root"

type CheckFolderViaGatedRootInputs struct {
  User []User
  Group []Group
  Role []Role
  Caveats CheckFolderViaGatedRootCaveats
}
type CheckFolderViaGatedRootCaveats struct {
  TenantMatch *TenantMatchArgs
}

func (folder Folder) CheckViaGatedRoot(ctx context.Context, input CheckFolderViaGatedRootInputs) (bool, error) {
  if len(input.User) == 0 && len(input.Group) == 0 && len(input.Role) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderViaGatedRoot), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  if len(input.Group) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderViaGatedRoot), TypeGroup, authz.IDs(input.Group), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  if len(input.Role) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderViaGatedRoot), TypeRole, authz.IDs(input.Role), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupViaGatedRootFolderResources(ctx context.Context, input CheckFolderViaGatedRootInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderViaGatedRoot),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  if len(input.Group) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderViaGatedRoot),
      TypeGroup, authz.IDs(input.Group),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  if len(input.Role) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderViaGatedRoot),
      TypeRole, authz.IDs(input.Role),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderEliteAccess PermissionFolder = "elite_access"

type CheckFolderEliteAccessInputs struct {
  User []User
  Caveats CheckFolderEliteAccessCaveats
}
type CheckFolderEliteAccessCaveats struct {
  HasToken *HasTokenArgs
  MinScore *MinScoreArgs
}

func (folder Folder) CheckEliteAccess(ctx context.Context, input CheckFolderEliteAccessInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderEliteAccess), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupEliteAccessFolderResources(ctx context.Context, input CheckFolderEliteAccessInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderEliteAccess),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderScoredMinusToken PermissionFolder = "scored_minus_token"

type CheckFolderScoredMinusTokenInputs struct {
  User []User
  Caveats CheckFolderScoredMinusTokenCaveats
}
type CheckFolderScoredMinusTokenCaveats struct {
  HasToken *HasTokenArgs
  MinScore *MinScoreArgs
}

func (folder Folder) CheckScoredMinusToken(ctx context.Context, input CheckFolderScoredMinusTokenInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderScoredMinusToken), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupScoredMinusTokenFolderResources(ctx context.Context, input CheckFolderScoredMinusTokenInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := input.Caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderScoredMinusToken),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderExpiringBrowse PermissionFolder = "expiring_browse"

type CheckFolderExpiringBrowseInputs struct {
  User []User
}

func (folder Folder) CheckExpiringBrowse(ctx context.Context, input CheckFolderExpiringBrowseInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderExpiringBrowse), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupExpiringBrowseFolderResources(ctx context.Context, input CheckFolderExpiringBrowseInputs) ([]Folder, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeFolder, authz.Permission(FolderExpiringBrowse),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderGatedTokenCheck PermissionFolder = "gated_token_check"

type CheckFolderGatedTokenCheckInputs struct {
  User []User
  Caveats CheckFolderGatedTokenCheckCaveats
}
type CheckFolderGatedTokenCheckCaveats struct {
  TenantMatch *TenantMatchArgs
}

func (folder Folder) CheckGatedTokenCheck(ctx context.Context, input CheckFolderGatedTokenCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderGatedTokenCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupGatedTokenCheckFolderResources(ctx context.Context, input CheckFolderGatedTokenCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderGatedTokenCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderPublicBrowse PermissionFolder = "public_browse"

type CheckFolderPublicBrowseInputs struct {
  User []User
}

func (folder Folder) CheckPublicBrowse(ctx context.Context, input CheckFolderPublicBrowseInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderPublicBrowse), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupPublicBrowseFolderResources(ctx context.Context, input CheckFolderPublicBrowseInputs) ([]Folder, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeFolder, authz.Permission(FolderPublicBrowse),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}
const FolderPublicGatedCheck PermissionFolder = "public_gated_check"

type CheckFolderPublicGatedCheckInputs struct {
  User []User
  Caveats CheckFolderPublicGatedCheckCaveats
}
type CheckFolderPublicGatedCheckCaveats struct {
  TenantMatch *TenantMatchArgs
}

func (folder Folder) CheckPublicGatedCheck(ctx context.Context, input CheckFolderPublicGatedCheckInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    }, authz.Permission(FolderPublicGatedCheck), TypeUser, authz.IDs(input.User), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupPublicGatedCheckFolderResources(ctx context.Context, input CheckFolderPublicGatedCheckInputs) ([]Folder, error) {

  var caveatCtx map[string]any
  if c := input.Caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResourcesWithCaveat(ctx,
      TypeFolder, authz.Permission(FolderPublicGatedCheck),
      TypeUser, authz.IDs(input.User),
      caveatCtx,
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Folder](ids), nil
  }
  
  return []Folder{}, nil
}

func (folder Folder) LookupBrowseUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupBrowseUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeUser,
  )
}
func (folder Folder) LookupBrowseGroupSubjects(ctx context.Context) ([]Group, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeGroup,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Group](ids), nil
}

func (folder Folder) LookupBrowseGroupWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeGroup,
  )
}
func (folder Folder) LookupBrowseRoleSubjects(ctx context.Context) ([]Role, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeRole,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Role](ids), nil
}

func (folder Folder) LookupBrowseRoleWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderBrowse), TypeRole,
  )
}

func (folder Folder) LookupTenantedBrowseUserSubjects(ctx context.Context, caveats CheckFolderTenantedBrowseCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderTenantedBrowse), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupTenantedBrowseUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderTenantedBrowse), TypeUser,
  )
}

func (folder Folder) LookupGuardedBrowseUserSubjects(ctx context.Context, caveats CheckFolderGuardedBrowseCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderGuardedBrowse), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupGuardedBrowseUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderGuardedBrowse), TypeUser,
  )
}

func (folder Folder) LookupActUserSubjects(ctx context.Context, caveats CheckFolderActCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderAct), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupActUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderAct), TypeUser,
  )
}

func (folder Folder) LookupCollaborateUserSubjects(ctx context.Context, caveats CheckFolderCollaborateCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderCollaborate), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupCollaborateUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderCollaborate), TypeUser,
  )
}
func (folder Folder) LookupCollaborateGroupSubjects(ctx context.Context, caveats CheckFolderCollaborateCaveats) ([]Group, error) {

  var caveatCtx map[string]any
  if c := caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderCollaborate), TypeGroup,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Group](ids), nil
}

func (folder Folder) LookupCollaborateGroupWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderCollaborate), TypeGroup,
  )
}

func (folder Folder) LookupRateCheckUserSubjects(ctx context.Context, caveats CheckFolderRateCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.QuotaCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MaxUses != nil {
      caveatCtx["max_uses"] = *c.MaxUses
    }
    if c.WithinQuota != nil {
      caveatCtx["within_quota"] = *c.WithinQuota
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderRateCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupRateCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderRateCheck), TypeUser,
  )
}

func (folder Folder) LookupScoreCheckUserSubjects(ctx context.Context, caveats CheckFolderScoreCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderScoreCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupScoreCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderScoreCheck), TypeUser,
  )
}

func (folder Folder) LookupTokenCheckUserSubjects(ctx context.Context, caveats CheckFolderTokenCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderTokenCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupTokenCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderTokenCheck), TypeUser,
  )
}

func (folder Folder) LookupVersionCheckPermUserSubjects(ctx context.Context, caveats CheckFolderVersionCheckPermCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.VersionCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.MinVersion != nil {
      caveatCtx["min_version"] = *c.MinVersion
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderVersionCheckPerm), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupVersionCheckPermUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderVersionCheckPerm), TypeUser,
  )
}

func (folder Folder) LookupMatrixCheckPermUserSubjects(ctx context.Context, caveats CheckFolderMatrixCheckPermCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.MatrixCheck; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Rows != nil {
      caveatCtx["rows"] = c.Rows
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderMatrixCheckPerm), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupMatrixCheckPermUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderMatrixCheckPerm), TypeUser,
  )
}

func (folder Folder) LookupMultiCheckUserSubjects(ctx context.Context, caveats CheckFolderMultiCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }
  if c := caveats.WithinWindow; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.AllowedActions != nil {
      caveatCtx["allowed_actions"] = c.AllowedActions
    }
    if c.RequestedAction != nil {
      caveatCtx["requested_action"] = *c.RequestedAction
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderMultiCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupMultiCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderMultiCheck), TypeUser,
  )
}

func (folder Folder) LookupViaGatedRootUserSubjects(ctx context.Context, caveats CheckFolderViaGatedRootCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupViaGatedRootUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeUser,
  )
}
func (folder Folder) LookupViaGatedRootGroupSubjects(ctx context.Context, caveats CheckFolderViaGatedRootCaveats) ([]Group, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeGroup,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Group](ids), nil
}

func (folder Folder) LookupViaGatedRootGroupWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeGroup,
  )
}
func (folder Folder) LookupViaGatedRootRoleSubjects(ctx context.Context, caveats CheckFolderViaGatedRootCaveats) ([]Role, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeRole,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Role](ids), nil
}

func (folder Folder) LookupViaGatedRootRoleWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderViaGatedRoot), TypeRole,
  )
}

func (folder Folder) LookupEliteAccessUserSubjects(ctx context.Context, caveats CheckFolderEliteAccessCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderEliteAccess), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupEliteAccessUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderEliteAccess), TypeUser,
  )
}

func (folder Folder) LookupScoredMinusTokenUserSubjects(ctx context.Context, caveats CheckFolderScoredMinusTokenCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.HasToken; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Token != nil {
      caveatCtx["token"] = c.Token
    }
  }
  if c := caveats.MinScore; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Current != nil {
      caveatCtx["current"] = *c.Current
    }
    if c.MinRequired != nil {
      caveatCtx["min_required"] = *c.MinRequired
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderScoredMinusToken), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupScoredMinusTokenUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderScoredMinusToken), TypeUser,
  )
}

func (folder Folder) LookupExpiringBrowseUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderExpiringBrowse), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupExpiringBrowseUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderExpiringBrowse), TypeUser,
  )
}

func (folder Folder) LookupGatedTokenCheckUserSubjects(ctx context.Context, caveats CheckFolderGatedTokenCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderGatedTokenCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupGatedTokenCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderGatedTokenCheck), TypeUser,
  )
}

func (folder Folder) LookupPublicBrowseUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderPublicBrowse), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupPublicBrowseUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderPublicBrowse), TypeUser,
  )
}

func (folder Folder) LookupPublicGatedCheckUserSubjects(ctx context.Context, caveats CheckFolderPublicGatedCheckCaveats) ([]User, error) {

  var caveatCtx map[string]any
  if c := caveats.TenantMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Tenant != nil {
      caveatCtx["tenant"] = *c.Tenant
    }
  }

  ids, err := authz.GetEngine(ctx).LookupSubjectsWithCaveat(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderPublicGatedCheck), TypeUser,
    caveatCtx,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (folder Folder) LookupPublicGatedCheckUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeFolder,
      ID: authz.ID(folder),
    },
    authz.Permission(FolderPublicGatedCheck), TypeUser,
  )
}
