// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  
)

const TypeGroup authz.Type = "extsvc/group"
type RelationGroup authz.Relation
type PermissionGroup authz.Permission


type Group authz.ID
func GroupStringer(id authz.StringConvertable) Group {
  return Group(id.String())
}

func GroupStringers(ids ...authz.StringConvertable) []Group {
  result := []Group{}
  for _, id := range ids {
    result = append(result, Group(id.String()))
  }
  return result
}

func (group Group) ToList() []Group {
  return []Group{ group }
}


