// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "errors"
  "fmt"
)

const TypeGroup authz.Type = "extsvc/group"
type RelationGroup authz.Relation
type PermissionGroup authz.Permission


type Group authz.ID

type GroupLookupResult struct {
  Definite    []Group
  Conditional []GroupConditionalLookupEntry
}
type GroupConditionalLookupEntry struct {
  ID          Group
  MissingKeys []string
}

func GroupStringer(id authz.StringConvertable) Group {
  return Group(id.String())
}

func GroupStringers(ids ...authz.StringConvertable) []Group {
  result := []Group{}
  for _, id := range ids {
    result = append(result, Group(id.String()))
  }
  return result
}

func (group Group) ToList() []Group {
  return []Group{ group }
}


// PurgeRelationsAsSubject deletes every relationship where this Group is the
// subject, across the resource types whose schema allows Group as a subject.
// One transactional delete per referencing resource type; failures are
// accumulated (errors.Join) and the rest still run — re-run on error
// (idempotent). Use it when this Group is deleted from your store,
// alongside PurgeRelations if Group also has relations.
func (group Group) PurgeRelationsAsSubject(ctx context.Context) error {
  eng := authz.GetEngine(ctx)
  var errs []error
  if err := eng.DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: authz.Type("extsvc/document"),
    SubjectType: TypeGroup,
    SubjectID: authz.ID(group),
  }); err != nil {
    errs = append(errs, fmt.Errorf("purge Group as subject of extsvc/document: %w", err))
  }
  if err := eng.DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: authz.Type("extsvc/folder"),
    SubjectType: TypeGroup,
    SubjectID: authz.ID(group),
  }); err != nil {
    errs = append(errs, fmt.Errorf("purge Group as subject of extsvc/folder: %w", err))
  }
  return errors.Join(errs...)
}

