// Code generated by spicedb-gen, DO NOT EDIT.

package extsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "time"
)

const TypeTeam authz.Type = "extsvc/team"
type RelationTeam authz.Relation
type PermissionTeam authz.Permission

const TeamOwner RelationTeam = "owner"
type TeamOwnerObjects struct {
  User []User
}
const TeamManager RelationTeam = "manager"
type TeamManagerObjects struct {
  User []User
}

type Team authz.ID
func TeamStringer(id authz.StringConvertable) Team {
  return Team(id.String())
}

func TeamStringers(ids ...authz.StringConvertable) []Team {
  result := []Team{}
  for _, id := range ids {
    result = append(result, Team(id.String()))
  }
  return result
}

func (team Team) ToList() []Team {
  return []Team{ team }
}

func (team Team) CreateOwnerRelations(ctx context.Context, objects TeamOwnerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    }, authz.Relation(TeamOwner), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}
func (team Team) CreateManagerRelations(ctx context.Context, objects TeamManagerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    }, authz.Relation(TeamManager), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (team Team) DeleteOwnerRelations(ctx context.Context, objects TeamOwnerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    }, authz.Relation(TeamOwner), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (team Team) DeleteManagerRelations(ctx context.Context, objects TeamManagerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    }, authz.Relation(TeamManager), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

type TeamOwnerUserRelation struct {
  ID            User
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r TeamOwnerUserRelation) RelationID() User { return r.ID }

func (team Team) ReadOwnerUserRelations(ctx context.Context) ([]TeamOwnerUserRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeTeam,
    ID: authz.ID(team),
  }, authz.Relation(TeamOwner), TypeUser)
  if err != nil {
    return nil, err
  }

  rels := make([]TeamOwnerUserRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, TeamOwnerUserRelation{
      ID:            User(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

type TeamManagerUserRelation struct {
  ID            User
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r TeamManagerUserRelation) RelationID() User { return r.ID }

func (team Team) ReadManagerUserRelations(ctx context.Context) ([]TeamManagerUserRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeTeam,
    ID: authz.ID(team),
  }, authz.Relation(TeamManager), TypeUser)
  if err != nil {
    return nil, err
  }

  rels := make([]TeamManagerUserRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, TeamManagerUserRelation{
      ID:            User(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

const TeamAdmin PermissionTeam = "admin"

type CheckTeamAdminInputs struct {
  User []User
}

func (team Team) CheckAdmin(ctx context.Context, input CheckTeamAdminInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    }, authz.Permission(TeamAdmin), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupAdminTeamResources(ctx context.Context, input CheckTeamAdminInputs) ([]Team, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeTeam, authz.Permission(TeamAdmin),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Team](ids), nil
  }
  
  return []Team{}, nil
}

func (team Team) LookupAdminUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    },
    authz.Permission(TeamAdmin), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (team Team) LookupAdminUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeTeam,
      ID: authz.ID(team),
    },
    authz.Permission(TeamAdmin), TypeUser,
  )
}
