// Code generated by spicedb-gen, DO NOT EDIT.

package bookingsvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
)

const TypeBooking authz.Type = "bookingsvc/booking"
type RelationBooking authz.Relation
type PermissionBooking authz.Permission

const BookingOwner RelationBooking = "owner"
type BookingOwnerObjects struct {
  Employee []Employee
}
const BookingCreator RelationBooking = "creator"
type BookingCreatorObjects struct {
  Employee []Employee
  Customer []Customer
}
const BookingRegionalOwner RelationBooking = "regional_owner"
type BookingRegionalOwnerObjects struct {
  Employee []Employee
  Caveats BookingRegionalOwnerCaveats
}
type BookingRegionalOwnerCaveats struct {
  Employee *RegionMatchArgs
}
type RegionMatchArgs struct {
  Region *string
}


type Booking authz.ID
func BookingStringer(id authz.StringConvertable) Booking {
  return Booking(id.String())
}

func BookingStringers(ids ...authz.StringConvertable) []Booking {
  result := []Booking{}
  for _, id := range ids {
    result = append(result, Booking(id.String()))
  }
  return result
}

func (booking Booking) ToList() []Booking {
  return []Booking{ booking }
}

func (booking Booking) CreateOwnerRelations(ctx context.Context, objects BookingOwnerObjects) error {
  if len(objects.Employee) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingOwner), TypeEmployee, authz.IDs(objects.Employee))
    if err != nil {
      return err
    }
  }
  return nil
}
func (booking Booking) CreateCreatorRelations(ctx context.Context, objects BookingCreatorObjects) error {
  if len(objects.Employee) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingCreator), TypeEmployee, authz.IDs(objects.Employee))
    if err != nil {
      return err
    }
  }
  if len(objects.Customer) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingCreator), TypeCustomer, authz.IDs(objects.Customer))
    if err != nil {
      return err
    }
  }
  return nil
}
func (booking Booking) CreateRegionalOwnerRelations(ctx context.Context, objects BookingRegionalOwnerObjects) error {
  if len(objects.Employee) > 0 {
    var caveatCtx map[string]any
    if c := objects.Caveats.Employee; c != nil {
      caveatCtx = map[string]any{}
      if c.Region != nil {
        caveatCtx["region"] = *c.Region
      }
    }
    err := authz.GetEngine(ctx).CreateRelationsWithCaveat(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingRegionalOwner), TypeEmployee, authz.IDs(objects.Employee), "bookingsvc/region_match", caveatCtx)
    if err != nil {
      return err
    }
  }
  return nil
}

func (booking Booking) DeleteOwnerRelations(ctx context.Context, objects BookingOwnerObjects) error {
  if len(objects.Employee) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingOwner), TypeEmployee, authz.IDs(objects.Employee))
    if err != nil {
      return err
    }
  }
  return nil
}

func (booking Booking) DeleteCreatorRelations(ctx context.Context, objects BookingCreatorObjects) error {
  if len(objects.Employee) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingCreator), TypeEmployee, authz.IDs(objects.Employee))
    if err != nil {
      return err
    }
  }
  if len(objects.Customer) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingCreator), TypeCustomer, authz.IDs(objects.Customer))
    if err != nil {
      return err
    }
  }
  return nil
}

func (booking Booking) DeleteRegionalOwnerRelations(ctx context.Context, objects BookingRegionalOwnerObjects) error {
  if len(objects.Employee) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Relation(BookingRegionalOwner), TypeEmployee, authz.IDs(objects.Employee))
    if err != nil {
      return err
    }
  }
  return nil
}

func (booking Booking) ReadOwnerEmployeeRelations(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeBooking,
    ID: authz.ID(booking),
  }, authz.Relation(BookingOwner), TypeEmployee)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

func (booking Booking) ReadCreatorEmployeeRelations(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeBooking,
    ID: authz.ID(booking),
  }, authz.Relation(BookingCreator), TypeEmployee)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

func (booking Booking) ReadCreatorCustomerRelations(ctx context.Context) ([]Customer, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeBooking,
    ID: authz.ID(booking),
  }, authz.Relation(BookingCreator), TypeCustomer)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Customer](ids), nil
}

func (booking Booking) ReadRegionalOwnerEmployeeRelations(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeBooking,
    ID: authz.ID(booking),
  }, authz.Relation(BookingRegionalOwner), TypeEmployee)
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

const BookingWrite PermissionBooking = "write"

type CheckBookingWriteInputs struct {
  Employee []Employee
  Customer []Customer
  User []User
}

func (booking Booking) CheckWrite(ctx context.Context, input CheckBookingWriteInputs) (bool, error) {
  if len(input.Employee) == 0 && len(input.Customer) == 0 && len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.Employee) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingWrite), TypeEmployee, authz.IDs(input.Employee))
    if err != nil {
      return false, err
    }
  }
  if len(input.Customer) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingWrite), TypeCustomer, authz.IDs(input.Customer))
    if err != nil {
      return false, err
    }
  }
  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingWrite), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupWriteBookingResources(ctx context.Context, input CheckBookingWriteInputs) ([]Booking, error) {
  if len(input.Employee) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingWrite), 
      TypeEmployee, authz.IDs(input.Employee),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  if len(input.Customer) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingWrite), 
      TypeCustomer, authz.IDs(input.Customer),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingWrite), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  
  return []Booking{}, nil
}
const BookingChangeOwner PermissionBooking = "change_owner"

type CheckBookingChangeOwnerInputs struct {
  Employee []Employee
  Customer []Customer
  User []User
}

func (booking Booking) CheckChangeOwner(ctx context.Context, input CheckBookingChangeOwnerInputs) (bool, error) {
  if len(input.Employee) == 0 && len(input.Customer) == 0 && len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.Employee) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingChangeOwner), TypeEmployee, authz.IDs(input.Employee))
    if err != nil {
      return false, err
    }
  }
  if len(input.Customer) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingChangeOwner), TypeCustomer, authz.IDs(input.Customer))
    if err != nil {
      return false, err
    }
  }
  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingChangeOwner), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupChangeOwnerBookingResources(ctx context.Context, input CheckBookingChangeOwnerInputs) ([]Booking, error) {
  if len(input.Employee) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingChangeOwner), 
      TypeEmployee, authz.IDs(input.Employee),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  if len(input.Customer) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingChangeOwner), 
      TypeCustomer, authz.IDs(input.Customer),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingChangeOwner), 
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  
  return []Booking{}, nil
}
const BookingRegionalWrite PermissionBooking = "regional_write"

type CheckBookingRegionalWriteInputs struct {
  Employee []Employee
  Caveats CheckBookingRegionalWriteCaveats
}
type CheckBookingRegionalWriteCaveats struct {
  RegionMatch *RegionMatchArgs
}

func (booking Booking) CheckRegionalWrite(ctx context.Context, input CheckBookingRegionalWriteInputs) (bool, error) {
  if len(input.Employee) == 0 && true {
    return false, authz.ErrNoInput
  }

  var caveatCtx map[string]any
  if c := input.Caveats.RegionMatch; c != nil {
    if caveatCtx == nil {
      caveatCtx = map[string]any{}
    }
    if c.Region != nil {
      caveatCtx["region"] = *c.Region
    }
  }

  if len(input.Employee) > 0 {
    err := authz.GetEngine(ctx).CheckPermissionWithCaveat(ctx, authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    }, authz.Permission(BookingRegionalWrite), TypeEmployee, authz.IDs(input.Employee), caveatCtx)
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupRegionalWriteBookingResources(ctx context.Context, input CheckBookingRegionalWriteInputs) ([]Booking, error) {
  if len(input.Employee) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeBooking, authz.Permission(BookingRegionalWrite), 
      TypeEmployee, authz.IDs(input.Employee),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Booking](ids), nil
  }
  
  return []Booking{}, nil
}

func (booking Booking) LookupWriteEmployeeSubjects(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeEmployee,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

func (booking Booking) LookupWriteEmployeeWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeEmployee,
  )
}
func (booking Booking) LookupWriteCustomerSubjects(ctx context.Context) ([]Customer, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeCustomer,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Customer](ids), nil
}

func (booking Booking) LookupWriteCustomerWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeCustomer,
  )
}
func (booking Booking) LookupWriteUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (booking Booking) LookupWriteUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingWrite), TypeUser,
  )
}

func (booking Booking) LookupChangeOwnerEmployeeSubjects(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeEmployee,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

func (booking Booking) LookupChangeOwnerEmployeeWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeEmployee,
  )
}
func (booking Booking) LookupChangeOwnerCustomerSubjects(ctx context.Context) ([]Customer, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeCustomer,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Customer](ids), nil
}

func (booking Booking) LookupChangeOwnerCustomerWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeCustomer,
  )
}
func (booking Booking) LookupChangeOwnerUserSubjects(ctx context.Context) ([]User, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (booking Booking) LookupChangeOwnerUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingChangeOwner), TypeUser,
  )
}

func (booking Booking) LookupRegionalWriteEmployeeSubjects(ctx context.Context) ([]Employee, error) {
  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingRegionalWrite), TypeEmployee,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[Employee](ids), nil
}

func (booking Booking) LookupRegionalWriteEmployeeWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeBooking,
      ID: authz.ID(booking),
    },
    authz.Permission(BookingRegionalWrite), TypeEmployee,
  )
}
