// Code generated by spicedb-gen, DO NOT EDIT.

package bookingsvc

import (
	"context"
	"errors"
	"fmt"
	"sort"

	"github.com/open-policy-agent/opa/v1/ast"
	"github.com/open-policy-agent/opa/v1/rego"
	"github.com/open-policy-agent/opa/v1/types"
	"google.golang.org/protobuf/types/known/structpb"

	"github.com/danhtran94/authzed-codegen/pkg/authz"
)

// SpiceDBBuiltins returns the OPA registration options for every
// SpiceDB-backed builtin in this package. Pass the result to rego.New
// alongside other options:
//
//	opts := []func(*rego.Rego){rego.Query(...), rego.Module(...)}
//	opts = append(opts, bookingsvc.SpiceDBBuiltins(engine, ctx)...)
//	r := rego.New(opts...)
//
// Builtin signatures:
//   bookingsvc.check_<resource>_<perm>(subject, resource_id, caveat_context) -> bool
//   bookingsvc.lookup_<resource>_<perm>_resources(subject, caveat_context) -> []string
//
// `subject` is an object keyed by SpiceDB subject type, value a single id
// string or a list of id strings — e.g. {"bookingsvc/user": "alice"} or
// {"bookingsvc/user": ["a","b"], "bookingsvc/group": ["g"]}. The keys are
// declared in the builtin Decl as exactly the permission's allowed subject
// types, so OPA rejects unknown keys at policy-compile time. Check is AND
// across present keys (every present subject type must be granted) —
// matching the typed Check<X> method. Lookup uses the first present key.
// `caveat_context` is always required; pass {} when no caveat applies.
// authz.ErrPermissionDenied / authz.ErrConditionalPermission map to
// BooleanTerm(false); any other engine error fails the Rego eval.
//
// Lookup builtins return LookupResult.Definite only; Conditional entries
// are not surfaced to Rego.
//
// For runtime.NewRuntime callers, use RegisterSpiceDBBuiltinsGlobal instead —
// runtime.NewRuntime has no hook for per-instance builtin options; it picks
// up builtins only from OPA's process-global registry.
//
// The closures capture engine and ctx by reference. Build a fresh option
// slice per request OR reuse a long-lived ctx for many evals — the
// codegen leaves the choice to the caller.
func SpiceDBBuiltins(engine authz.Engine, ctx context.Context) []func(*rego.Rego) {
	return []func(*rego.Rego){
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_booking_change_owner",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("change_owner")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_booking_change_owner_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("change_owner")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_booking_regional_write",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("regional_write")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_booking_regional_write_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("regional_write")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_booking_write",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("write")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_booking_write_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("write")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_brand_create_booking",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/brand"), ID: authz.ID(resID)}
				perm := authz.Permission("create_booking")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_brand_create_booking_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/brand")
				perm := authz.Permission("create_booking")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_brand_manage",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/brand"), ID: authz.ID(resID)}
				perm := authz.Permission("manage")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_brand_manage_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/brand")
				perm := authz.Permission("manage")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_employee_manage",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/employee"), ID: authz.ID(resID)}
				perm := authz.Permission("manage")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_employee_manage_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/employee")
				perm := authz.Permission("manage")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
		rego.Function3(
			&rego.Function{
				Name: "bookingsvc.check_employee_view",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
			func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/employee"), ID: authz.ID(resID)}
				perm := authz.Permission("view")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
		),
		rego.Function2(
			&rego.Function{
				Name: "bookingsvc.lookup_employee_view_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
			func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/employee")
				perm := authz.Permission("view")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
		),
	}
}

// RegisterSpiceDBBuiltinsGlobal registers every SpiceDB-backed builtin in
// this package into OPA's process-global builtin registry (ast.Builtins +
// ast.BuiltinMap + the topdown function map) via rego.RegisterBuiltin2/3.
// This is what runtime.NewRuntime and the standard /v1/data endpoint need:
// they have no hook for per-instance rego.Function* options, but any
// compiler built afterward (including the runtime's, via plugins.New →
// ast.NewCompiler) reads the global builtin universe.
//
// Call this ONCE at startup, before any concurrent compilation.
// ast.RegisterBuiltin is not concurrency-safe (OPA's source warns of
// "concurrent map read/write panics"). Calling it more than once appends
// duplicate entries to ast.Builtins.
//
// Builtin signatures (object-keyed subject; see SpiceDBBuiltins above),
// error mapping, and Definite-only Lookup behavior are identical to
// SpiceDBBuiltins — only the registration mechanism differs (process-global
// vs per-instance). The closures capture engine and ctx by reference; the
// global variant bakes them in process-wide.
func RegisterSpiceDBBuiltinsGlobal(engine authz.Engine, ctx context.Context) {
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_booking_change_owner",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("change_owner")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_booking_change_owner_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("change_owner")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_booking_regional_write",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("regional_write")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_booking_regional_write_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("regional_write")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_booking_write",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/booking"), ID: authz.ID(resID)}
				perm := authz.Permission("write")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_booking_write_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/booking")
				perm := authz.Permission("write")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_brand_create_booking",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/brand"), ID: authz.ID(resID)}
				perm := authz.Permission("create_booking")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_brand_create_booking_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/brand")
				perm := authz.Permission("create_booking")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_brand_manage",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/brand"), ID: authz.ID(resID)}
				perm := authz.Permission("manage")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_brand_manage_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/brand")
				perm := authz.Permission("manage")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_employee_manage",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/employee"), ID: authz.ID(resID)}
				perm := authz.Permission("manage")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_employee_manage_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/employee")
				perm := authz.Permission("manage")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
	rego.RegisterBuiltin3(
		&rego.Function{
				Name: "bookingsvc.check_employee_view",
				Decl: types.NewFunction(
					types.Args(
						// subject: object keyed by SpiceDB subject type, value
						// a string id or a list of string ids. Fully dynamic —
						// OPA's static-property object types are effectively
						// required-all, so per-permission key sets can't be
						// declared without breaking single-key calls; bogus
						// subject types surface as a runtime error from SpiceDB.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.S,
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.B,
				),
			},
		func(_ rego.BuiltinContext, subjTerm, resTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				resID, ok := resTerm.Value.(ast.String)
				if !ok {
					return nil, fmt.Errorf("expected resource_id string, got %T", resTerm.Value)
				}
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.BooleanTerm(false), nil
				}

				res := authz.Resource{Type: authz.Type("bookingsvc/employee"), ID: authz.ID(resID)}
				perm := authz.Permission("view")
				// AND across present subject-type keys — matches the typed
				// Check<X> method, which short-circuits to false on the first
				// non-granted subject slice. (Single-key call: this is just one check.)
				for _, e := range entries {
					var checkErr error
					if caveatCtx == nil {
						checkErr = engine.CheckPermission(ctx, res, perm, authz.Type(e.Namespace), e.IDs)
					} else {
						ctxMap := structpbToMap(caveatCtx)
						checkErr = engine.CheckPermissionWithCaveat(ctx, res, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
					}
					granted, fatal := checkOneGranted(checkErr)
					if fatal != nil {
						return nil, fatal
					}
					if !granted {
						return ast.BooleanTerm(false), nil
					}
				}
				return ast.BooleanTerm(true), nil
			},
	)
	rego.RegisterBuiltin2(
		&rego.Function{
				Name: "bookingsvc.lookup_employee_view_resources",
				Decl: types.NewFunction(
					types.Args(
						// subject: see check_* above — same object shape.
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.NewAny(types.S, types.NewArray(nil, types.S)))),
						types.NewObject(nil, types.NewDynamicProperty(types.S, types.A)),
					),
					types.NewArray(nil, types.S),
				),
			},
		func(_ rego.BuiltinContext, subjTerm, ctxTerm *ast.Term) (*ast.Term, error) {
				entries, err := subjectEntries(subjTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid subject: %v", err)
				}
				caveatCtx, err := termToStructpb(ctxTerm)
				if err != nil {
					return nil, fmt.Errorf("invalid caveat_context: %v", err)
				}
				if len(entries) == 0 {
					return ast.ArrayTerm(), nil
				}
				// First present subject-type key wins — matches the typed
				// Lookup<Perm><Resource>Resources method. Pass exactly one
				// key for predictable results.
				e := entries[0]
				resType := authz.Type("bookingsvc/employee")
				perm := authz.Permission("view")
				// Returns LookupResult.Definite only; Conditional entries dropped per
				// scope-opa-go-builtins-codegen.md Out of Scope item 8.
				var result authz.LookupResult
				if caveatCtx == nil {
					result, err = engine.LookupResources(ctx, resType, perm, authz.Type(e.Namespace), e.IDs)
				} else {
					ctxMap := structpbToMap(caveatCtx)
					result, err = engine.LookupResourcesWithCaveat(ctx, resType, perm, authz.Type(e.Namespace), e.IDs, ctxMap)
				}
				if err != nil {
					return nil, fmt.Errorf("LookupResources: %v", err)
				}
				terms := make([]*ast.Term, len(result.Definite))
				for i, id := range result.Definite {
					terms[i] = ast.StringTerm(string(id))
				}
				return ast.ArrayTerm(terms...), nil
			},
	)
}

// subjectEntry is one (subject type, ids) pair parsed from the subject
// object argument.
type subjectEntry struct {
	Namespace string
	IDs       []authz.ID
}

// subjectEntries parses the subject object {"<namespace>": id | [id, ...]}
// into entries sorted by namespace (deterministic — OPA's ast.Object
// iteration order is not). Returns an error if the term is not an object,
// has a non-string key, or a value that isn't a string or list of strings.
func subjectEntries(t *ast.Term) ([]subjectEntry, error) {
	obj, ok := t.Value.(ast.Object)
	if !ok {
		return nil, subjectError(`subject must be an object {"<type>": id | [id, ...]}`)
	}
	var entries []subjectEntry
	var iterErr error
	obj.Foreach(func(k, v *ast.Term) {
		if iterErr != nil {
			return
		}
		ks, ok := k.Value.(ast.String)
		if !ok {
			iterErr = subjectError("subject keys must be strings")
			return
		}
		ids, err := idsFromTerm(v)
		if err != nil {
			iterErr = err
			return
		}
		entries = append(entries, subjectEntry{Namespace: string(ks), IDs: ids})
	})
	if iterErr != nil {
		return nil, iterErr
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Namespace < entries[j].Namespace })
	return entries, nil
}

// idsFromTerm normalizes a subject value (a string id, or a list of string
// ids) to []authz.ID.
func idsFromTerm(t *ast.Term) ([]authz.ID, error) {
	switch v := t.Value.(type) {
	case ast.String:
		return []authz.ID{authz.ID(v)}, nil
	case *ast.Array:
		out := make([]authz.ID, 0, v.Len())
		for i := 0; i < v.Len(); i++ {
			s, ok := v.Elem(i).Value.(ast.String)
			if !ok {
				return nil, subjectError("subject id list must contain only strings")
			}
			out = append(out, authz.ID(s))
		}
		return out, nil
	default:
		return nil, subjectError("subject value must be a string or list of strings")
	}
}

// checkOneGranted maps an Engine.CheckPermission return value to (granted,
// fatal). nil error → granted. authz.ErrPermissionDenied /
// authz.ErrConditionalPermission → not granted (policy signal, not a system
// error). Any other error is fatal — the caller fails the Rego eval so a
// SpiceDB outage is distinguishable from a policy denial (per SPEC-013 C4).
func checkOneGranted(err error) (granted bool, fatal error) {
	if err == nil {
		return true, nil
	}
	if errors.Is(err, authz.ErrPermissionDenied) || errors.Is(err, authz.ErrConditionalPermission) {
		return false, nil
	}
	return false, fmt.Errorf("CheckPermission: %v", err)
}

// termToStructpb converts an OPA ast.Term holding an Object to a
// *structpb.Struct. Returns (nil, nil) for empty objects so the caller
// dispatches to the no-caveat Engine path. Returns an error if the term
// is not an Object or contains values not representable in structpb.
func termToStructpb(t *ast.Term) (*structpb.Struct, error) {
	obj, ok := t.Value.(ast.Object)
	if !ok {
		return nil, errMalformedCaveatContext
	}
	if obj.Len() == 0 {
		return nil, nil
	}
	m := make(map[string]any, obj.Len())
	var iterErr error
	obj.Foreach(func(k, v *ast.Term) {
		if iterErr != nil {
			return
		}
		ks, ok := k.Value.(ast.String)
		if !ok {
			iterErr = errMalformedCaveatContext
			return
		}
		val, err := astValueToInterface(v.Value)
		if err != nil {
			iterErr = err
			return
		}
		m[string(ks)] = val
	})
	if iterErr != nil {
		return nil, iterErr
	}
	return structpb.NewStruct(m)
}

type subjectError string

func (e subjectError) Error() string { return string(e) }

var errMalformedCaveatContext = subjectError("caveat_context must be an object with string keys")

// astValueToInterface walks an ast.Value and returns the Go any equivalent
// suitable for structpb.NewStruct.
func astValueToInterface(v ast.Value) (any, error) {
	switch x := v.(type) {
	case ast.Null:
		return nil, nil
	case ast.Boolean:
		return bool(x), nil
	case ast.Number:
		if i, ok := x.Int64(); ok {
			return i, nil
		}
		f, ok := x.Float64()
		if !ok {
			return nil, subjectError("number out of range")
		}
		return f, nil
	case ast.String:
		return string(x), nil
	case *ast.Array:
		out := make([]any, 0, x.Len())
		for i := 0; i < x.Len(); i++ {
			val, err := astValueToInterface(x.Elem(i).Value)
			if err != nil {
				return nil, err
			}
			out = append(out, val)
		}
		return out, nil
	case ast.Object:
		out := make(map[string]any, x.Len())
		var iterErr error
		x.Foreach(func(k, vt *ast.Term) {
			if iterErr != nil {
				return
			}
			ks, ok := k.Value.(ast.String)
			if !ok {
				iterErr = errMalformedCaveatContext
				return
			}
			val, err := astValueToInterface(vt.Value)
			if err != nil {
				iterErr = err
				return
			}
			out[string(ks)] = val
		})
		if iterErr != nil {
			return nil, iterErr
		}
		return out, nil
	case ast.Set:
		return nil, subjectError("ast.Set is not representable in structpb")
	default:
		return nil, subjectError("unsupported ast value type")
	}
}

// structpbToMap unwraps a *structpb.Struct back to map[string]any for the
// Engine APIs that take a Go map (CheckPermissionWithCaveat / LookupResourcesWithCaveat).
func structpbToMap(s *structpb.Struct) map[string]any {
	if s == nil {
		return nil
	}
	return s.AsMap()
}
