// Code generated by spicedb-gen, DO NOT EDIT.

package menusvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "time"
)

const TypeCompany authz.Type = "menusvc/company"
type RelationCompany authz.Relation
type PermissionCompany authz.Permission

const CompanyAdmin RelationCompany = "admin"
type CompanyAdminObjects struct {
  User []User
}
const CompanyManager RelationCompany = "manager"
type CompanyManagerObjects struct {
  User []User
}
const CompanyEmployee RelationCompany = "employee"
type CompanyEmployeeObjects struct {
  User []User
}

type Company authz.ID
func CompanyStringer(id authz.StringConvertable) Company {
  return Company(id.String())
}

func CompanyStringers(ids ...authz.StringConvertable) []Company {
  result := []Company{}
  for _, id := range ids {
    result = append(result, Company(id.String()))
  }
  return result
}

func (company Company) ToList() []Company {
  return []Company{ company }
}

func (company Company) CreateAdminRelations(ctx context.Context, objects CompanyAdminObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyAdmin), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}
func (company Company) CreateManagerRelations(ctx context.Context, objects CompanyManagerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyManager), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}
func (company Company) CreateEmployeeRelations(ctx context.Context, objects CompanyEmployeeObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyEmployee), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (company Company) DeleteAdminRelations(ctx context.Context, objects CompanyAdminObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyAdmin), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (company Company) DeleteManagerRelations(ctx context.Context, objects CompanyManagerObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyManager), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

func (company Company) DeleteEmployeeRelations(ctx context.Context, objects CompanyEmployeeObjects) error {
  if len(objects.User) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Relation(CompanyEmployee), TypeUser, authz.IDs(objects.User))
    if err != nil {
      return err
    }
  }
  return nil
}

type CompanyAdminUserRelation struct {
  ID            User
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r CompanyAdminUserRelation) RelationID() User { return r.ID }

func (company Company) ReadAdminUserRelations(ctx context.Context) ([]CompanyAdminUserRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeCompany,
    ID: authz.ID(company),
  }, authz.Relation(CompanyAdmin), TypeUser)
  if err != nil {
    return nil, err
  }

  rels := make([]CompanyAdminUserRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, CompanyAdminUserRelation{
      ID:            User(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

type CompanyManagerUserRelation struct {
  ID            User
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r CompanyManagerUserRelation) RelationID() User { return r.ID }

func (company Company) ReadManagerUserRelations(ctx context.Context) ([]CompanyManagerUserRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeCompany,
    ID: authz.ID(company),
  }, authz.Relation(CompanyManager), TypeUser)
  if err != nil {
    return nil, err
  }

  rels := make([]CompanyManagerUserRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, CompanyManagerUserRelation{
      ID:            User(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

type CompanyEmployeeUserRelation struct {
  ID            User
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r CompanyEmployeeUserRelation) RelationID() User { return r.ID }

func (company Company) ReadEmployeeUserRelations(ctx context.Context) ([]CompanyEmployeeUserRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypeCompany,
    ID: authz.ID(company),
  }, authz.Relation(CompanyEmployee), TypeUser)
  if err != nil {
    return nil, err
  }

  rels := make([]CompanyEmployeeUserRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, CompanyEmployeeUserRelation{
      ID:            User(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

const CompanyManage PermissionCompany = "manage"

type CheckCompanyManageInputs struct {
  User []User
}

func (company Company) CheckManage(ctx context.Context, input CheckCompanyManageInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Permission(CompanyManage), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupManageCompanyResources(ctx context.Context, input CheckCompanyManageInputs) ([]Company, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeCompany, authz.Permission(CompanyManage),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Company](ids), nil
  }
  
  return []Company{}, nil
}
const CompanyCreateBooking PermissionCompany = "create_booking"

type CheckCompanyCreateBookingInputs struct {
  User []User
}

func (company Company) CheckCreateBooking(ctx context.Context, input CheckCompanyCreateBookingInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Permission(CompanyCreateBooking), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupCreateBookingCompanyResources(ctx context.Context, input CheckCompanyCreateBookingInputs) ([]Company, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeCompany, authz.Permission(CompanyCreateBooking),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Company](ids), nil
  }
  
  return []Company{}, nil
}
const CompanyCreateOrder PermissionCompany = "create_order"

type CheckCompanyCreateOrderInputs struct {
  User []User
}

func (company Company) CheckCreateOrder(ctx context.Context, input CheckCompanyCreateOrderInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    }, authz.Permission(CompanyCreateOrder), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupCreateOrderCompanyResources(ctx context.Context, input CheckCompanyCreateOrderInputs) ([]Company, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypeCompany, authz.Permission(CompanyCreateOrder),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Company](ids), nil
  }
  
  return []Company{}, nil
}

func (company Company) LookupManageUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyManage), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (company Company) LookupManageUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyManage), TypeUser,
  )
}

func (company Company) LookupCreateBookingUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyCreateBooking), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (company Company) LookupCreateBookingUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyCreateBooking), TypeUser,
  )
}

func (company Company) LookupCreateOrderUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyCreateOrder), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (company Company) LookupCreateOrderUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypeCompany,
      ID: authz.ID(company),
    },
    authz.Permission(CompanyCreateOrder), TypeUser,
  )
}
