// Code generated by spicedb-gen, DO NOT EDIT.

package menusvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "errors"
  "fmt"
)

const TypeCustomer authz.Type = "menusvc/customer"
type RelationCustomer authz.Relation
type PermissionCustomer authz.Permission


type Customer authz.ID

type CustomerLookupResult struct {
  Definite    []Customer
  Conditional []CustomerConditionalLookupEntry
}
type CustomerConditionalLookupEntry struct {
  ID          Customer
  MissingKeys []string
}

func CustomerStringer(id authz.StringConvertable) Customer {
  return Customer(id.String())
}

func CustomerStringers(ids ...authz.StringConvertable) []Customer {
  result := []Customer{}
  for _, id := range ids {
    result = append(result, Customer(id.String()))
  }
  return result
}

func (customer Customer) ToList() []Customer {
  return []Customer{ customer }
}


// PurgeRelationsAsSubject deletes every relationship where this Customer is the
// subject, across the resource types whose schema allows Customer as a subject.
// One transactional delete per referencing resource type; failures are
// accumulated (errors.Join) and the rest still run — re-run on error
// (idempotent). Use it when this Customer is deleted from your store,
// alongside PurgeRelations if Customer also has relations.
func (customer Customer) PurgeRelationsAsSubject(ctx context.Context) error {
  eng := authz.GetEngine(ctx)
  var errs []error
  if err := eng.DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: authz.Type("menusvc/booking"),
    SubjectType: TypeCustomer,
    SubjectID: authz.ID(customer),
  }); err != nil {
    errs = append(errs, fmt.Errorf("purge Customer as subject of menusvc/booking: %w", err))
  }
  if err := eng.DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: authz.Type("menusvc/order"),
    SubjectType: TypeCustomer,
    SubjectID: authz.ID(customer),
  }); err != nil {
    errs = append(errs, fmt.Errorf("purge Customer as subject of menusvc/order: %w", err))
  }
  return errors.Join(errs...)
}

