// Code generated by spicedb-gen, DO NOT EDIT.

package menusvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "time"
)

const TypePricelist authz.Type = "menusvc/pricelist"
type RelationPricelist authz.Relation
type PermissionPricelist authz.Permission

const PricelistOwner RelationPricelist = "owner"
type PricelistOwnerObjects struct {
  Company []Company
}

type Pricelist authz.ID
func PricelistStringer(id authz.StringConvertable) Pricelist {
  return Pricelist(id.String())
}

func PricelistStringers(ids ...authz.StringConvertable) []Pricelist {
  result := []Pricelist{}
  for _, id := range ids {
    result = append(result, Pricelist(id.String()))
  }
  return result
}

func (pricelist Pricelist) ToList() []Pricelist {
  return []Pricelist{ pricelist }
}

func (pricelist Pricelist) CreateOwnerRelations(ctx context.Context, objects PricelistOwnerObjects) error {
  if len(objects.Company) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Relation(PricelistOwner), TypeCompany, authz.IDs(objects.Company))
    if err != nil {
      return err
    }
  }
  return nil
}

func (pricelist Pricelist) DeleteOwnerRelations(ctx context.Context, objects PricelistOwnerObjects) error {
  if len(objects.Company) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Relation(PricelistOwner), TypeCompany, authz.IDs(objects.Company))
    if err != nil {
      return err
    }
  }
  return nil
}

type PricelistOwnerCompanyRelation struct {
  ID            Company
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r PricelistOwnerCompanyRelation) RelationID() Company { return r.ID }

func (pricelist Pricelist) ReadOwnerCompanyRelations(ctx context.Context) ([]PricelistOwnerCompanyRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypePricelist,
    ID: authz.ID(pricelist),
  }, authz.Relation(PricelistOwner), TypeCompany)
  if err != nil {
    return nil, err
  }

  rels := make([]PricelistOwnerCompanyRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, PricelistOwnerCompanyRelation{
      ID:            Company(t.ID),
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

const PricelistWrite PermissionPricelist = "write"

type CheckPricelistWriteInputs struct {
  User []User
}

func (pricelist Pricelist) CheckWrite(ctx context.Context, input CheckPricelistWriteInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Permission(PricelistWrite), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupWritePricelistResources(ctx context.Context, input CheckPricelistWriteInputs) ([]Pricelist, error) {

  if len(input.User) > 0 {
    ids, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypePricelist, authz.Permission(PricelistWrite),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return nil, err
    }

    return authz.FromIDs[Pricelist](ids), nil
  }
  
  return []Pricelist{}, nil
}

func (pricelist Pricelist) LookupWriteUserSubjects(ctx context.Context) ([]User, error) {

  ids, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    },
    authz.Permission(PricelistWrite), TypeUser,
  )
  if err != nil {
    return nil, err
  }

  return authz.FromIDsExcludingWildcard[User](ids), nil
}

func (pricelist Pricelist) LookupWriteUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    },
    authz.Permission(PricelistWrite), TypeUser,
  )
}
