// Code generated by spicedb-gen, DO NOT EDIT.

package menusvc

import (
  "github.com/danhtran94/authzed-codegen/pkg/authz"

  "context"
  "time"
)

const TypePricelist authz.Type = "menusvc/pricelist"
type RelationPricelist authz.Relation
type PermissionPricelist authz.Permission

const PricelistOwner RelationPricelist = "owner"
type PricelistOwnerObjects struct {
  Company []Company
}

type Pricelist authz.ID

type PricelistLookupResult struct {
  Definite    []Pricelist
  Conditional []PricelistConditionalLookupEntry
}
type PricelistConditionalLookupEntry struct {
  ID          Pricelist
  MissingKeys []string
}

func PricelistStringer(id authz.StringConvertable) Pricelist {
  return Pricelist(id.String())
}

func PricelistStringers(ids ...authz.StringConvertable) []Pricelist {
  result := []Pricelist{}
  for _, id := range ids {
    result = append(result, Pricelist(id.String()))
  }
  return result
}

func (pricelist Pricelist) ToList() []Pricelist {
  return []Pricelist{ pricelist }
}

func (pricelist Pricelist) CreateOwnerRelations(ctx context.Context, objects PricelistOwnerObjects) error {
  if len(objects.Company) > 0 {
    err := authz.GetEngine(ctx).CreateRelations(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Relation(PricelistOwner), TypeCompany, authz.IDs(objects.Company))
    if err != nil {
      return err
    }
  }
  return nil
}

func (pricelist Pricelist) DeleteOwnerRelations(ctx context.Context, objects PricelistOwnerObjects) error {
  if len(objects.Company) > 0 {
    err := authz.GetEngine(ctx).DeleteRelations(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Relation(PricelistOwner), TypeCompany, authz.IDs(objects.Company))
    if err != nil {
      return err
    }
  }
  return nil
}

// PurgeOwnerRelations deletes every owner relationship on this
// Pricelist, regardless of subject — clears the relation entirely. Unlike
// DeleteOwnerRelations (which revokes the specific subjects you pass),
// use this when owner as a whole no longer applies to this Pricelist.
func (pricelist Pricelist) PurgeOwnerRelations(ctx context.Context) error {
  return authz.GetEngine(ctx).DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: TypePricelist,
    ResourceID: authz.ID(pricelist),
    Relation: authz.Relation(PricelistOwner),
  })
}

// PurgeRelations deletes every relationship on this Pricelist — all relations,
// any subject — in one transaction. Use it when this Pricelist is deleted from
// your store: it removes the Pricelist's resource-side tuples. It does NOT
// remove tuples where this Pricelist appears as a *subject* of another
// resource — for that, see PurgeRelationsAsSubject (emitted when Pricelist is a
// subject anywhere in the schema).
func (pricelist Pricelist) PurgeRelations(ctx context.Context) error {
  return authz.GetEngine(ctx).DeleteRelationsMatching(ctx, authz.RelationFilter{
    ResourceType: TypePricelist,
    ResourceID: authz.ID(pricelist),
  })
}

type PricelistOwnerCompanyRelation struct {
  ID            Company
  SubRelation   string
  CaveatName    string
  CaveatContext map[string]any
  ExpiresAt     *time.Time
}
func (r PricelistOwnerCompanyRelation) RelationID() Company { return r.ID }

func (pricelist Pricelist) ReadOwnerCompanyRelations(ctx context.Context) ([]PricelistOwnerCompanyRelation, error) {
  tuples, err := authz.GetEngine(ctx).ReadRelations(ctx, authz.Resource{
    Type: TypePricelist,
    ID: authz.ID(pricelist),
  }, authz.Relation(PricelistOwner), TypeCompany)
  if err != nil {
    return nil, err
  }

  rels := make([]PricelistOwnerCompanyRelation, 0, len(tuples))
  for _, t := range tuples {
    if t.ID == authz.WildcardID {
      continue
    }
    rels = append(rels, PricelistOwnerCompanyRelation{
      ID:            Company(t.ID),
      SubRelation:   t.SubRelation,
      CaveatName:    t.CaveatName,
      CaveatContext: t.CaveatContext,
      ExpiresAt:     t.ExpiresAt,
    })
  }
  return rels, nil
}

const PricelistWrite PermissionPricelist = "write"

type CheckPricelistWriteInputs struct {
  User []User
}

func (pricelist Pricelist) CheckWrite(ctx context.Context, input CheckPricelistWriteInputs) (bool, error) {
  if len(input.User) == 0 && true {
    return false, authz.ErrNoInput
  }

  if len(input.User) > 0 {
    err := authz.GetEngine(ctx).CheckPermission(ctx, authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    }, authz.Permission(PricelistWrite), TypeUser, authz.IDs(input.User))
    if err != nil {
      return false, err
    }
  }
  
  return true, nil
}

func LookupWritePricelistResources(ctx context.Context, input CheckPricelistWriteInputs) (PricelistLookupResult, error) {

  if len(input.User) > 0 {
    result, err := authz.GetEngine(ctx).LookupResources(ctx,
      TypePricelist, authz.Permission(PricelistWrite),
      TypeUser, authz.IDs(input.User),
    )
    if err != nil {
      return PricelistLookupResult{}, err
    }

    out := PricelistLookupResult{
      Definite:    authz.FromIDs[Pricelist](result.Definite),
      Conditional: make([]PricelistConditionalLookupEntry, 0, len(result.Conditional)),
    }
    for _, c := range result.Conditional {
      out.Conditional = append(out.Conditional, PricelistConditionalLookupEntry{
        ID:          Pricelist(c.ID),
        MissingKeys: c.MissingKeys,
      })
    }
    return out, nil
  }
  
  return PricelistLookupResult{}, nil
}

func (pricelist Pricelist) LookupWriteUserSubjects(ctx context.Context) (UserLookupResult, error) {

  result, err := authz.GetEngine(ctx).LookupSubjects(ctx,
    authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    },
    authz.Permission(PricelistWrite), TypeUser,
  )
  if err != nil {
    return UserLookupResult{}, err
  }

  out := UserLookupResult{
    Definite:    authz.FromIDsExcludingWildcard[User](result.Definite),
    Conditional: make([]UserConditionalLookupEntry, 0, len(result.Conditional)),
  }
  for _, c := range result.Conditional {
    out.Conditional = append(out.Conditional, UserConditionalLookupEntry{
      ID:          User(c.ID),
      MissingKeys: c.MissingKeys,
    })
  }
  return out, nil
}

func (pricelist Pricelist) LookupWriteUserWildcardSubjects(ctx context.Context) (bool, error) {
  return authz.GetEngine(ctx).HasPublicSubject(ctx,
    authz.Resource{
      Type: TypePricelist,
      ID: authz.ID(pricelist),
    },
    authz.Permission(PricelistWrite), TypeUser,
  )
}
