package generator

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/danhtran94/authzed-codegen/internal/utilstr"
)

var SOURCE_HEADER = "// Code generated by spicedb-gen, DO NOT EDIT.\n\n"

type Generator struct {
	Definitions     []*DefinitionView
	ObjectTemplates map[string]string

	OutputPath string
}

func NewGenerator(definitions []*DefinitionView) *Generator {
	return &Generator{Definitions: definitions, ObjectTemplates: make(map[string]string)}
}

func (g *Generator) AddObjectTemplate(name, template string) {
	g.ObjectTemplates[name] = template
}

func (g *Generator) GenerateObjectSource(name string) error {
	tmplStr := g.ObjectTemplates[name]

	defs := ParseDefinitions(g.Definitions)
	tree := defs.GetPermissionTree()

	var mapFuncs = template.FuncMap{
		"upperFirst":    utilstr.UpperFirst,
		"packageName":   utilstr.PackageName,
		"snakeToPascal": utilstr.SnakeToPascal,
		"typeName":      utilstr.TypeName,
		"permissionInputTypes": func(objectType string, perm string) []string {
			treename := fmt.Sprintf("%s/%s", objectType, perm)
			if types, ok := tree[treename]; ok {
				return types
			}
			return []string{}
		},
	}

	tmpl := template.New(name).Funcs(mapFuncs)

	tmpl, err := tmpl.Parse(tmplStr)
	if err != nil {
		return err
	}

	for _, def := range g.Definitions {
		path := fmt.Sprintf("%s/%s", g.OutputPath, utilstr.PackageName(def.ObjectType.Prefix))
		err := os.MkdirAll(path, os.ModePerm)
		if err != nil {
			return err
		}
	}

	for _, def := range g.Definitions {
		buf := bytes.Buffer{}

		_, err := buf.WriteString(SOURCE_HEADER)
		if err != nil {
			return err
		}

		err = tmpl.Execute(&buf, struct {
			*DefinitionView
		}{
			DefinitionView: def,
		})
		if err != nil {
			return nil
		}

		filePath := fmt.Sprintf("%s/%s/%s.gen.go", g.OutputPath, utilstr.PackageName(def.ObjectType.Prefix), utilstr.PackageName(def.ObjectType.Name))
		err = os.WriteFile(filePath, buf.Bytes(), os.ModePerm)
		if err != nil {
			return err
		}
	}

	return nil
}

type Permission struct {
	Types []string
	Kind  string
	Value string
}

type Relation struct {
	Types []string
	Kind  string
	Value string
}

type Permissions []Permission
type PermissionsByNames map[string]Permissions

func (p PermissionsByNames) IsEmpty() bool {
	return len(p) == 0
}

func (p PermissionsByNames) Get(permission string) (bool, Permissions) {
	if perms, ok := p[permission]; ok {
		return true, perms
	}
	return false, []Permission{}
}

type Relations []Relation
type RelationsByNames map[string]Relations

func (r RelationsByNames) Get(relation string) (bool, Relations) {
	if rels, ok := r[relation]; ok {
		return true, rels
	}
	return false, []Relation{}
}

func (r Relations) Types() []string {
	types := []string{}
	for _, rel := range r {
		types = append(types, rel.Types...)
	}
	return types
}

type Definition struct {
	Type        string
	Permissions PermissionsByNames
	Relations   RelationsByNames
}

type DefinitionsByTypes map[string]*Definition

func (d DefinitionsByTypes) GetPermissionTree() map[string][]string {
	tree := map[string][]string{}
	seen := map[string]bool{}

	addTree := func(treename string, types []string) {
		for _, t := range types {
			seenname := fmt.Sprintf("%s/%s", treename, t)
			if _, ok := seen[seenname]; !ok {
				seen[seenname] = true
				tree[treename] = append(tree[treename], t)
			}
		}
	}

	relationResolver := map[string][]string{}
	for t, def := range d {
		if def.Permissions.IsEmpty() {
			tree[t] = []string{}
		}

		for n, permissions := range def.Permissions {
			for _, p := range permissions {
				if p.Kind == "relation" {
					treename := fmt.Sprintf("%s/%s", t, n)
					relationResolver[treename] = p.Types
				}
			}
		}
	}

	for t, def := range d {
		for n, permissions := range def.Permissions {
			for _, p := range permissions {
				treename := fmt.Sprintf("%s/%s", t, n)
				if p.Kind == "permission" {
					for _, ref := range p.Types {
						refperm := fmt.Sprintf("%s/%s", ref, p.Value)
						addTree(treename, relationResolver[refperm])
					}
				} else {
					addTree(treename, p.Types)
				}
			}
		}
	}

	return tree
}

func ParseDefinitions(defs []*DefinitionView) DefinitionsByTypes {
	defsByTypes := DefinitionsByTypes{}

	for _, d := range defs {
		objectType := d.ObjectType.String()
		_permissions := PermissionsByNames{}
		_relations := RelationsByNames{}

		for _, p := range d.Permissions {
			_permissions[p.Name] = Permissions{}
		}

		for _, r := range d.Relations {
			_relations[r.Name] = relationFromView(r)
		}

		defsByTypes[objectType] = &Definition{
			Type:        objectType,
			Permissions: _permissions,
			Relations:   _relations,
		}
	}

	for _, d := range defs {
		objectType := d.ObjectType.String()
		_permissions := PermissionsByNames{}

		for _, p := range d.Permissions {
			_permissions[p.Name] = resolvePermissionExpressionTypes(p.Expressions, ResolveArgs{
				ObjectType:  objectType,
				Definitions: defsByTypes,
			})
		}

		defsByTypes[objectType].Permissions = _permissions
	}

	return defsByTypes
}

// relationFromView lifts a RelationView's flat AllowedTypes into the
// existing []Relation shape consumed by GetPermissionTree. Each allowed
// type becomes its own Relation row, mirroring the per-arm expansion the
// old AST walker produced for `a | b | c` expressions.
func relationFromView(r *RelationView) Relations {
	out := make(Relations, 0, len(r.AllowedTypes))
	for _, t := range r.AllowedTypes {
		out = append(out, Relation{
			Types: []string{t},
			Kind:  "single",
			Value: t,
		})
	}
	return out
}

type ResolveArgs struct {
	ObjectType  string
	Definitions DefinitionsByTypes
}

func resolvePermissionExpressionTypes(exprs []PermissionExpr, args ResolveArgs) []Permission {
	permissions := []Permission{}

	_relations := args.Definitions[args.ObjectType].Relations
	_permissions := args.Definitions[args.ObjectType].Permissions

	for _, e := range exprs {
		switch e.Kind {
		case PermExprIdentifier:
			if ok, rels := _relations.Get(e.Ident); ok {
				permissions = append(permissions, Permission{
					Types: rels.Types(),
					Kind:  "relation",
					Value: e.Ident,
				})
			} else if ok, _ := _permissions.Get(e.Ident); ok {
				permissions = append(permissions, Permission{
					Types: []string{args.ObjectType},
					Kind:  "permission",
					Value: e.Ident,
				})
			}

		case PermExprArrow:
			_, relations := _relations.Get(e.LeftRel)
			for _, referenceType := range relations.Types() {
				refDef, ok := args.Definitions[referenceType]
				if !ok {
					continue
				}
				if ok, _ := refDef.Permissions.Get(e.RightPerm); ok {
					permissions = append(permissions, Permission{
						Types: []string{referenceType},
						Kind:  "permission",
						Value: e.RightPerm,
					})
				}
			}
		}
	}

	deduped := []Permission{}
	seen := map[string]bool{}
	for _, p := range permissions {
		uniq := strings.Join(p.Types, ",") + p.Kind + p.Value
		if _, ok := seen[uniq]; !ok {
			seen[uniq] = true
			deduped = append(deduped, p)
		}
	}

	return deduped
}
